name: Minecraft Docker Image CI

on:
  workflow_dispatch:
    inputs:
      LATEST_VERSION:
        description: '要构建的Minecraft版本；只打版本镜像且会跳过`检查版本是否更新`和`记录最后构建版本`步骤'
        required: false
        default: ''
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Clone MinecraftForge Repository
      run: |
        git clone --depth 1 --recurse-submodules https://github.com/MinecraftForge/MinecraftForge.git

    - name: Checkout MinecraftForge Version
      run: |
        cd MinecraftForge
        git fetch --all --tags
        MC_VERSION="${{ github.event.inputs.LATEST_VERSION }}"
        # 检查是否存在与 Minecraft 版本对应的 Forge tag 分支
        if git rev-parse "refs/tags/$MC_VERSION" >/dev/null 2>&1; then
          git checkout "tags/$MC_VERSION"
        else
          echo "Version $MC_VERSION not found, exiting."
          exit 1
        fi

    - name: Build MinecraftForge
      run: |
        cd MinecraftForge
        ./gradlew setup
        ./gradlew build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: forge-jar
        path: MinecraftForge/build/libs/*.jar
