name: Minecraft Docker Image CI

on:
  workflow_dispatch:
    inputs:
      LATEST_VERSION:
        description: '要构建的Minecraft版本；只打版本镜像且会跳过`检查版本是否更新`和`记录最后构建版本`步骤'
        required: false
        default: ''
        type: string

jobs:
  get_forge_version:
    runs-on: ubuntu-latest
    steps:
      - name: 获取Forge版本信息
        run: |
          response=$(curl -s "https://files.minecraftforge.net/net/minecraftforge/forge/")
          if [ $? -ne 0 ]; then
              echo "curl failed: $($?)"
              echo "$response"
              exit 1
          fi
          minecraft_version=${{ github.event.inputs.SERVER_VERSION }}
          #尝试更简单的正则表达式，先找到所有版本号
          versions=$(echo "$response" | grep -oE "${minecraft_version}/[0-9.]+/")
          if [ -z "$versions" ]; then
              echo "No Forge version found for Minecraft ${minecraft_version}"
              exit 1
          fi
          
          #提取版本号并排序，选择最新的
          latest_version=$(echo "$versions" | sed 's/.*\///' | sort -V | tail -n 1)
          
          latest_forge_url="${url}${minecraft_version}/${latest_version}/forge-${minecraft_version}-${latest_version}-installer.jar"
          echo "最新Forge版本下载链接：${latest_forge_url}"
        shell: bash
      - name: 输出最新Forge版本下载链接
        run: |
          echo "最新Forge版本下载链接：${latest_forge_url}"
        shell: bash
