name: Minecraft Docker Image CI

on:
  workflow_dispatch:
    inputs:
      LATEST_VERSION:
        description: '要构建的Minecraft版本；只打版本镜像且会跳过`检查版本是否更新`和`记录最后构建版本`步骤'
        required: false
        default: ''
        type: string

jobs:
  get_forge_version:
    runs-on: ubuntu-latest
    steps:
      - name: 获取Forge版本信息
        run: |
          url="https://files.minecraftforge.net/net/minecraftforge/forge/"
          response=$(curl -s -f "$url")
          if [ $? -ne 0 ]; then
            echo "Failed to retrieve Forge version information"
            exit 1
          fi
          minecraft_version=${{ github.event.inputs.LATEST_VERSION }}
          latest_forge_version=$(echo "$response" | grep -oP "(?<=${minecraft_version}/).*?(?=/)" | sort -V | tail -1)
          if [ -z "$latest_forge_version" ]; then
            echo "No Forge version found for Minecraft ${minecraft_version}"
            exit 1
          fi
          latest_forge_url="${url}${minecraft_version}/${latest_forge_version}/forge-${minecraft_version}-${latest_forge_version}-installer.jar"
          echo "最新Forge版本下载链接：${latest_forge_url=${latest_forge_url}"
        shell: bash
      - name: 输出最新Forge版本下载链接
        run: |
          echo "最新Forge版本下载链接：${latest_forge_url}"
        shell: bash
