name: Upload to Tencent COS

on: 
  push:
    branches:
      - main-fabric

jobs:
  upload_to_cos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install COS CLI
      run: |
        curl -o coscli.sh -sSL https://cloud.tencent.com/document/product/436/62774
        bash coscli.sh

    - name: Upload to Tencent COS
      run: |
        coscli cp -r ./expand cos://${{ env.COS_BUCKET_NAME }}/minecraft/
      env:
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        COS_REGION: ap-guangzhou
        COS_BUCKET_NAME: system-1302599754
