name: Upload to Tencent COS

on:
  workflow_dispatch:

jobs:
  upload_to_cos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install COS CLI
      run: |
        curl -o coscli -sSL https://cosbrowser.cloud.tencent.com/software/coscli/coscli-v1.0.0-linux-amd64
        chmod 755 coscli
        ./coscli --version

    - name: Configure COS CLI
      run: |
        ./coscli config init -i ${{ secrets.TENCENT_SECRET_ID }} -k ${{ secrets.TENCENT_SECRET_KEY }} \
        -b ${{ COS_BUCKET_NAME }} -r ${{ COS_REGION }} -e ${{ COS_ENDPOINT_NAME }}
      env:
        COS_REGION: ap-guangzhou
        COS_BUCKET_NAME: system-1302599754
        COS_ENDPOINT_NAME: cos.ap-guangzhou.myqcloud.com
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}

    - name: Upload to Tencent COS
      run: |
        ./coscli cp -r ./expand cos://${{ env.COS_BUCKET_NAME }}/minecraft/
      env:
        COS_BUCKET_NAME: system-1302599754
